name: Build and Push MSSQL Docker Image

on:
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - main   # or your working branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set platform for M1/M2 compatibility
      run: echo "DOCKER_DEFAULT_PLATFORM=linux/amd64" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mssql -f database-mssql/docker/Dockerfile database-mssql

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mssql